obstacle_range: 2.5
raytrace_range: 3.0

#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]

robot_radius: 0.5

inflation_radius: 0.55

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud2, topic: topic_name, marking: true, clearing: true}